const router = require('express').Router();
const c = require('../controllers/employerController');
const jobs = require('../controllers/jobController');
const billing = require('../controllers/billingController');
const v = require('../validators/employerValidator');
const ev = require('../validators/evaluationValidator');
const jv = require('../validators/jobValidator');
const { validate } = require('../middleware/validateMiddleware');
const { authenticate, requireVerifiedEmail } = require('../middleware/authMiddleware');
const { requireRole, loadEmployer, requireEmployerRole } = require('../middleware/roleMiddleware');
const upload = require('../middleware/uploadMiddleware');
const notifications = require('../services/notificationService');
const h = require('../utils/asyncHandler');
const { ok } = require('../utils/response');

const managers = requireEmployerRole('Owner', 'HR Manager');
const hiring = requireEmployerRole('Owner', 'HR Manager', 'Recruiter');

router.use(authenticate, requireRole('employer'), requireVerifiedEmail, loadEmployer);
router.get('/profile', c.profile);
router.put('/profile', managers, validate(v.profile), c.updateProfile);
router.get('/dashboard', c.dashboard);
router.post('/verify-candidate', hiring, validate(v.verifyCandidate), c.verifyCandidate);
router.post('/verify-candidate/bulk', managers, upload.single('file'), c.bulkVerify);
router.get('/consents', c.consents);
router.post('/consents/:id/otp', hiring, validate(v.consentOtp), c.consentOtp);
router.post('/reports', hiring, validate(v.generateReport), c.generateReport);
router.get('/resumes/:id/download', c.downloadResume);
router.get('/reports', c.reports);
router.get('/reports/:id', c.getReport);
router.get('/questionnaire', c.questionnaire);
router.get('/employees', c.employees);
router.post('/employees', managers, validate(v.addEmployee), c.addEmployee);
router.post('/employments/:id/verify', managers, validate(v.verifyEmployment), c.verifyEmployment);
router.get('/evaluations', c.evaluations);
router.post('/evaluations', validate(ev.create), c.createEvaluation);
router.put('/evaluations/:id', validate(ev.update), c.updateEvaluation);
router.delete('/evaluations/:id', c.deleteEvaluation);
router.get('/talent', hiring, c.talent);
router.get('/team', c.team);
router.post('/team', requireEmployerRole('Owner'), validate(v.invite), c.invite);
router.put('/team/:id', requireEmployerRole('Owner'), validate(v.memberRole), c.updateMember);
router.delete('/team/:id', requireEmployerRole('Owner'), c.removeMember);
router.get('/usage', c.usage);
router.get('/audit-trail', managers, c.auditTrail);
router.get('/jobs', jobs.employerJobs);
router.post('/jobs', hiring, validate(jv.create), jobs.create);
router.put('/jobs/:id', hiring, validate(jv.update), jobs.update);
router.delete('/jobs/:id', hiring, jobs.remove);
router.get('/jobs/:id/applicants', hiring, jobs.applicants);
router.patch('/applications/:id/status', hiring, validate(jv.status), jobs.setStatus);
router.get('/invoices', billing.invoices);
router.get('/notifications', h(async (req, res) => ok(res, await notifications.list(req.user._id))));

module.exports = router;
