module.exports = {
  home: {
    title: 'Home',
    content: {
      announcement: '',
      hero: {
        badge: "India's Employment Score Bureau",
        title: "India's Employee Trust & Verification Network",
        subtitle: 'A verified, tamper-evident employment reputation score from 300 to 950. Employers verify and rate; professionals own a portable career identity they can see, rebut and dispute.',
        primaryCta: 'Start Verification',
        secondaryCta: 'Schedule Demo',
      },
      stats: [{ label: 'Score range', value: '300-950' }, { label: 'Baseline for verified profiles', value: '890' }, { label: 'Ledger', value: 'SHA-256 chained' }, { label: 'Consent-first reports', value: '100%' }],
      sampleProfiles: [
        { name: 'Aarav Mehta', role: 'Senior Product Engineer', score: 912, band: 'Prime Executive', background: 'Verified', integrity: 'A+', history: [{ company: 'Northwind Systems', years: '2021 - Present' }, { company: 'Bluepeak Labs', years: '2018 - 2021' }] },
        { name: 'Isha Kapoor', role: 'HR Business Partner', score: 864, band: 'Excellent', background: 'Verified', integrity: 'A', history: [{ company: 'Lotus Retail', years: '2020 - Present' }, { company: 'Crest Finance', years: '2017 - 2020' }] },
        { name: 'Rohan Iyer', role: 'Data Analyst', score: 781, band: 'Good', background: 'Verified', integrity: 'B+', history: [{ company: 'Orbit Analytics', years: '2022 - Present' }] },
      ],
      trustedBy: ['Northwind Systems', 'Bluepeak Labs', 'Lotus Retail', 'Crest Finance', 'Orbit Analytics', 'Sahyadri Infra'],
      trustedNote: 'Illustrative organisation names. Real logos are shown only with written permission.',
      steps: [
        { title: 'Register & verify identity', body: 'Sign up, confirm your email with an OTP and verify your PAN. One person, one PAN, one EIBIL profile.' },
        { title: 'Employers verify & rate', body: 'Approved employers confirm your employment and submit quarterly evaluations on performance, professionalism, reliability and conduct.' },
        { title: 'Your score updates', body: 'Every verified event is sealed in a hash-chained ledger and moves your score within seconds, with an as-of timestamp on every report.' },
      ],
      engine: [
        { title: 'Employee Verification', body: 'PAN-linked identity with HMAC de-duplication, employer-signed employment records and consent-logged checks.', icon: 'ShieldCheck' },
        { title: 'Fraud Detection', body: 'Duplicate PAN/email/mobile attempts, near-duplicate identities, overlapping employment and rating-pattern outliers.', icon: 'ScanSearch' },
        { title: 'Reputation Score', body: 'Configurable, versioned scoring from evaluations, exits, offers and tenure, reproducible by replaying the ledger.', icon: 'Gauge' },
        { title: 'AI Hiring Insights', body: 'Advisory-only signals to help recruiters focus. Never auto-rejects a candidate. (Coming in Phase 3.)', icon: 'Sparkles' },
      ],
      forEmployers: ['Consent-based candidate reports in minutes', 'Notice-period and rehire eligibility from sealed exit records', 'Quarterly evaluations with anti-abuse controls', 'Score-gated job posts and applicant pipeline'],
      forEmployees: ['Own a portable, verified career identity', 'See, rebut and dispute anything recorded about you', 'Easy Apply to score-gated jobs with one click', 'Control who sees your report and for how long'],
      testimonials: [
        { quote: 'We cut background-check turnaround from two weeks to a day, and candidates appreciate the consent-first flow.', name: 'Head of Talent', company: 'Illustrative mid-size IT services firm' },
        { quote: 'For the first time I could see exactly what a previous employer said about my exit, and add my side.', name: 'Senior Analyst', company: 'Illustrative EIBIL member' },
        { quote: 'The no-show and notice-period signals alone changed how we plan joining dates.', name: 'HR Director', company: 'Illustrative manufacturing group' },
      ],
      faq: [
        { q: 'What is the EIBIL score?', a: 'A verified employment reputation score between 300 and 950. New PAN-verified profiles start at a baseline of 890, and the score moves only through verified employer events and published rules.' },
        { q: 'Can an employer see my report without my permission?', a: 'No. Every report requires your recorded consent (on-demand, OTP-based or pre-granted when you apply to a job) and every view is logged and visible to you.' },
        { q: 'Is my salary visible to employers?', a: 'Never. Salary and CTC are stored only if you choose, and are never shown to other employers.' },
        { q: 'What if an evaluation is unfair?', a: 'You can raise a dispute with evidence. Disputed evaluations are held out of your score until an admin resolves them with a written outcome.' },
        { q: 'Why PAN?', a: 'PAN guarantees one person = one profile. We store only an encrypted PAN and a one-way hash; screens only ever show the masked form (ABCDE****F).' },
      ],
      cta: { title: 'Build hiring on verified trust', body: 'Start verifying candidates today, or claim your EIBIL profile in under five minutes.' },
      compliance: ['DPDP Act 2023 aligned consent & rights', 'AES-256-GCM encrypted PAN at rest', 'SHA-256 hash-chained, append-only ledger', 'ISO 27001 certification in progress (not yet certified)'],
    },
  },
  about: { title: 'About EIBIL', content: { heading: 'Trust, verified', body: 'EIBIL (Employment Integrity & Background Intelligence League) is building India’s employment score bureau. We give every professional a verified, portable career identity and give employers a consent-first way to hire on facts rather than guesswork.\n\nOur principles: one person, one PAN, one profile; every record append-only and tamper-evident; employees can always see, rebut and dispute; employers verify, rate and are held accountable through the Employer Trust Index.' } },
  platform: { title: 'Platform', content: { heading: 'One platform, three panels', body: 'Career Hub for professionals, Employer Console for HR teams and an Admin Console that governs verification, scoring, disputes, billing and content.' } },
  'score-system': { title: 'Score System', content: { heading: 'How the EIBIL score works', body: 'Composite = weighted average of Performance (30%), Professionalism (20%), Reliability (25%) and Conduct (25%). Evaluation delta = (Composite − 75) × 0.6, capped at ±25 per cycle and weighted by employer trust tier and recency. Exit assessments, verified no-shows, tenure milestones and dispute outcomes apply configurable boosts or penalties. Negative events decay after 36 months (serious fraud never decays).' } },
  'how-it-works': { title: 'How It Works', content: { heading: 'From registration to a living score', body: '1. Register and verify your email (OTP) and PAN.\n2. Declare employment; your employer verifies and seals it.\n3. Employers rate you quarterly; offers, exits and notice periods are recorded with your review rights.\n4. Your score updates on every verified event, and scheduled jobs keep it fresh.' } },
  csr: { title: 'CSR', content: { heading: 'Fair work, for everyone', body: 'Free EIBIL profiles for every professional, a transparent dispute process, and partnerships with skilling programmes to help first-time workers build verified histories.' } },
  pricing: { title: 'Pricing', content: { heading: 'Simple plans for every hiring team', body: 'Pay per verification credit or choose a plan. All prices exclusive of 18% GST.' } },
  contact: { title: 'Contact Us', content: { heading: 'Talk to the EIBIL team', body: 'Questions, demos or partnerships: write to us and we will respond within one business day.', email: 'support@eibil.in', phone: '+91 80 0000 0000', address: 'Bengaluru, Karnataka, India', grievanceOfficer: 'Grievance Officer, EIBIL - grievance@eibil.in' } },
  faq: { title: 'FAQ', content: { heading: 'Frequently asked questions', body: 'See the most common questions below. All answers are managed from the Admin CMS.' } },
  privacy: { title: 'Privacy Policy', type: 'legal', content: { heading: 'Privacy Policy', body: 'EIBIL processes personal data for the purpose of employment verification under explicit, logged consent, in line with the Digital Personal Data Protection Act, 2023. You may access, correct and request erasure of your data subject to legal retention. Contact our Grievance Officer at grievance@eibil.in. (Draft: subject to legal review before launch.)' } },
  terms: { title: 'Terms of Use', type: 'legal', content: { heading: 'Terms of Use', body: 'By using EIBIL you agree to provide accurate information, use reports only for lawful employment purposes with candidate consent, and keep evaluation language factual. (Draft: subject to legal review before launch.)' } },
  security: { title: 'Security', type: 'legal', content: { heading: 'Security at EIBIL', body: 'PAN encrypted with AES-256-GCM; unique HMAC-SHA256 hash for de-duplication; bcrypt password hashing; rotating refresh tokens; mandatory admin 2FA; rate limiting; signed, expiring document links; append-only SHA-256 hash-chained ledger with integrity verification.' } },
  compliance: { title: 'Compliance', type: 'legal', content: { heading: 'Compliance', body: 'DPDP Act 2023 aligned consent management, access logs and rights handling. ISO 27001 certification is being pursued and is not yet obtained. EIBIL does not use blockchain; records are anchored in an internal hash-chained ledger.' } },
};
